Feature/login page
YAPP13-4/semibasement-web-v2 pull request #22
Opened 2019-06-30 12:49 UTC by JungSeBin

### 목적 및 일정
login page 구현 중 context 구조 변경으로 인해 중간 merge가 필요
(~ 07.13 에 merge예정)

#### 기획
![default](https://via.placeholder.com/600x240)

### 이슈 번호
#21 , #9 

### 변경 사항
- user 관련 repository, redux, component 등등 api연동 필요한 파일들 추가,
- context분리 및 application class로 생성

### 이 PR로 영향을 받는 기능
- 

### 테스트 해야할 기능
- [ ]

2019-06-30 12:50 UTC, JungSeBin commented
중간에 develop을 merge 했으니 그부분도 살펴봐주셨으면 ㅎ

2019-07-07 08:49 UTC, SoYoung210 requested changes
duck typing을 쓰면 action, reducer, saga를 한파일로 작성할 수 있습니다. :) @JungSeBin

2019-07-07 08:49 UTC, SoYoung210 commented on src/api/user/mapper/userMeMapper/index.ts
> +type UserMeResponse = {
이건 따로 entity로 정의 안하나용?

2019-07-07 08:49 UTC, SoYoung210 commented on src/presentation/redux/actionTypes.ts
> +  USERS_ME: 'USERS_ME',
오잉? users/me 는 어떤 액션타입인가요? 추가적으로 USERS 아래에 어떤것들이 더 생긴다면 아래와같이 쓰는건 어떨까요
```js
USERS: {
  ME: USERS_ME
}
```

2019-07-07 08:49 UTC, SoYoung210 commented on src/presentation/redux/music/actions.ts
> +export const FAIL = `${PREFIX}/FAIL`;
duck typing으로 고고..?

2019-07-07 08:50 UTC, SoYoung210 commented
![image](https://user-images.githubusercontent.com/18658235/60766107-bc5eee80-a0df-11e9-8106-b8d828885dfd.png)

@JungSeBin 요러면 안돌아갈것 같습니다!

2019-07-07 08:52 UTC, JungSeBin commented on src/api/user/mapper/userMeMapper/index.ts
> +type UserMeResponse = {
response를 entity로 정희 안하냐는게 어떤 말인가요?

2019-07-07 08:53 UTC, JungSeBin commented on src/presentation/redux/actionTypes.ts
> +  USERS_ME: 'USERS_ME',
내가 로그인 돼있나 확인하는 API에 대한 action 입니다.
위 같은 구조가 더 좋은데 그럼 music도 같이 바껴야 할듯

2019-07-07 08:54 UTC, JungSeBin commented on src/presentation/redux/music/actions.ts
> +export const FAIL = `${PREFIX}/FAIL`;
duck 알못이라...

2019-07-07 08:54 UTC, SoYoung210 commented on src/api/user/mapper/userMeMapper/index.ts
> +type UserMeResponse = {
아 ,,, 잘못파악스 ! json 의 type 까지 적어주는 것은 타입 safe하긴 하지만, 이 부분은 api 명세 영역아닐까요?

2019-07-07 08:55 UTC, SoYoung210 commented on src/presentation/redux/actionTypes.ts
> +  USERS_ME: 'USERS_ME',
인정! MUSIC도
```js
MUSIC: {
  HOME: MUSIC_HOME
}
```

으로?

2019-07-07 08:59 UTC, JungSeBin commented on src/api/user/mapper/userMeMapper/index.ts
> +type UserMeResponse = {
기왕 type 쓰는거 safe하게 해봤어요 ㅋㅋ

2019-07-07 09:05 UTC, SoYoung210 commented on src/presentation/redux/music/actions.ts
> +export const FAIL = `${PREFIX}/FAIL`;
#23 을 참고해주세요! ㅎㅎ

2019-07-21 09:58 UTC, SoYoung210 approved these changes

2019-07-21 09:59 UTC, merged